### ISSUE TITLE
Value of type 'Ondato' has no member 'setCredentials'

### ISSUE THREAD

**Issue by Agnsemo** [ondato/ondato-sdk-ios#10]
I have username and password, but don't seem to find setCredentials anymore, to what it changed?

**Comment by Svaike** [comment]
Hi @Agnsemo!

You need to call IDV API with those credentials in order to create the user session. Then you pass id to: Ondato.sdk.setIdentityVerificationId("<Verification Id>")

Just a note you need to create a new session every time user starts a flow.

Let me know if you have any additional questions or contact support@ondato.com

**Comment by Agnsemo** [comment]
Is it still possible to access 1.8.23 version using cocoapods ?
